"use client";

import { FormEvent, useEffect, useState } from "react";
import { CheckCircle2, ClipboardList, ExternalLink, Plus, Send, XCircle } from "lucide-react";

type Task = { _id: string; title: string; description: string; dueDate?: string; assignedToId: string; assignedToName: string; assignedByName: string; status: "assigned" | "submitted" | "needs_improvement" | "completed"; submissionText?: string; submissionLink?: string; reviewerRemarks?: string; createdAt: string };
type Member = { clerkUserId: string; name: string; designation: string; isActive: boolean };
const labels = { assigned: "Assigned", submitted: "Awaiting review", needs_improvement: "Needs improvement", completed: "Completed" };
const colors = { assigned: "bg-sky-100 text-sky-700", submitted: "bg-amber-100 text-amber-700", needs_improvement: "bg-rose-100 text-rose-700", completed: "bg-emerald-100 text-emerald-700" };

async function request(url: string, init?: RequestInit) { const response = await fetch(url, { ...init, headers: { "Content-Type": "application/json" } }); const data = await response.json(); if (!response.ok) throw new Error(data.error || "Something went wrong"); return data; }

export function MyTasks() {
  const [tasks, setTasks] = useState<Task[]>([]); const [selected, setSelected] = useState<Task | null>(null); const [work, setWork] = useState(""); const [link, setLink] = useState(""); const [error, setError] = useState("");
  const load = () => request("/api/tasks").then((data) => setTasks(data.data)).catch((e) => setError(e.message));
  useEffect(() => { void load(); }, []);
  const submit = async (event: FormEvent) => { event.preventDefault(); if (!selected) return; try { await request(`/api/tasks/${selected._id}`, { method: "PATCH", body: JSON.stringify({ action: "submit", submissionText: work, submissionLink: link }) }); setSelected(null); setWork(""); setLink(""); load(); } catch (e) { setError(e instanceof Error ? e.message : "Could not submit task"); } };
  return <section className="space-y-4"><div><p className="text-xs font-semibold uppercase tracking-[.25em] text-slate-400">My Tasks</p><h2 className="mt-1 text-2xl font-bold text-slate-900">Work assigned to you</h2><p className="mt-1 text-sm text-slate-500">Submit your work here and track your reviewer’s feedback.</p></div>{error && <p className="rounded-xl bg-rose-50 p-3 text-sm text-rose-700">{error}</p>}<div className="grid gap-4 lg:grid-cols-2">{tasks.length === 0 ? <Empty /> : tasks.map((task) => <TaskCard key={task._id} task={task} action={<button onClick={() => { setSelected(task); setWork(task.submissionText || ""); setLink(task.submissionLink || ""); }} disabled={task.status === "completed"} className="rounded-xl bg-slate-900 px-4 py-2 text-sm font-medium text-white disabled:opacity-40">{task.status === "needs_improvement" ? "Resubmit" : "Submit work"}</button>} />)}</div>{selected && <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/40 p-4"><form onSubmit={submit} className="w-full max-w-xl rounded-3xl bg-white p-6 shadow-2xl"><h3 className="text-xl font-bold">Submit: {selected.title}</h3><textarea required={!link} value={work} onChange={(e) => setWork(e.target.value)} placeholder="Describe your completed work" className="mt-4 min-h-32 w-full rounded-xl border p-3 text-sm"/><input value={link} onChange={(e) => setLink(e.target.value)} placeholder="Submission link (optional if details provided)" className="mt-3 w-full rounded-xl border p-3 text-sm"/><div className="mt-4 flex justify-end gap-2"><button type="button" onClick={() => setSelected(null)} className="rounded-xl border px-4 py-2 text-sm">Cancel</button><button className="rounded-xl bg-slate-900 px-4 py-2 text-sm text-white">Send for review</button></div></form></div>}</section>;
}

export function AssignTasks({ members }: { members: Member[] }) {
  const [tasks, setTasks] = useState<Task[]>([]); const [error, setError] = useState(""); const [reviewing, setReviewing] = useState<Task | null>(null); const [remarks, setRemarks] = useState("");
  const load = () => request("/api/tasks").then((data) => setTasks(data.data)).catch((e) => setError(e.message)); useEffect(() => { void load(); }, []);
  const assign = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); try { await request("/api/tasks", { method: "POST", body: JSON.stringify(Object.fromEntries(form)) }); event.currentTarget.reset(); load(); } catch (e) { setError(e instanceof Error ? e.message : "Could not assign task"); } };
  const review = async (status: "completed" | "needs_improvement") => { if (!reviewing) return; try { await request(`/api/tasks/${reviewing._id}`, { method: "PATCH", body: JSON.stringify({ action: "review", status, reviewerRemarks: remarks }) }); setReviewing(null); setRemarks(""); load(); } catch (e) { setError(e instanceof Error ? e.message : "Could not review task"); } };
  return <div className="space-y-6"><div><p className="text-xs font-semibold uppercase tracking-[.25em] text-slate-400">Head workspace</p><h2 className="mt-1 text-2xl font-bold text-slate-900">Assign & review tasks</h2></div>{error && <p className="rounded-xl bg-rose-50 p-3 text-sm text-rose-700">{error}</p>}<form onSubmit={assign} className="grid gap-3 rounded-3xl border border-slate-200 bg-white p-5 shadow-sm md:grid-cols-2"><input name="title" required placeholder="Task title" className="rounded-xl border p-3 text-sm"/><select name="assignedToId" required className="rounded-xl border p-3 text-sm"><option value="">Assign to a member</option>{members.filter(m => m.isActive).map((m) => <option key={m.clerkUserId} value={m.clerkUserId}>{m.name} — {m.designation}</option>)}</select><textarea name="description" required placeholder="Task instructions and expected deliverables" className="min-h-28 rounded-xl border p-3 text-sm md:col-span-2"/><input type="date" name="dueDate" className="rounded-xl border p-3 text-sm"/><button className="inline-flex items-center justify-center gap-2 rounded-xl bg-slate-900 px-4 py-3 text-sm font-medium text-white"><Plus className="h-4 w-4"/>Assign task</button></form><div className="grid gap-4 lg:grid-cols-2">{tasks.length === 0 ? <Empty /> : tasks.map((task) => <TaskCard key={task._id} task={task} action={task.status === "submitted" ? <button onClick={() => { setReviewing(task); setRemarks(""); }} className="rounded-xl bg-slate-900 px-4 py-2 text-sm text-white">Review submission</button> : undefined} />)}</div>{reviewing && <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/40 p-4"><div className="w-full max-w-xl rounded-3xl bg-white p-6 shadow-2xl"><h3 className="text-xl font-bold">Review: {reviewing.title}</h3><p className="mt-3 rounded-xl bg-slate-50 p-3 text-sm whitespace-pre-wrap">{reviewing.submissionText || "No written details submitted."}</p>{reviewing.submissionLink && <a className="mt-2 inline-flex items-center gap-1 text-sm text-blue-700 underline" href={reviewing.submissionLink} target="_blank"><ExternalLink className="h-3 w-3"/>Open submission</a>}<textarea value={remarks} onChange={(e) => setRemarks(e.target.value)} placeholder="Remarks are required if requesting improvements" className="mt-4 min-h-24 w-full rounded-xl border p-3 text-sm"/><div className="mt-4 flex flex-wrap justify-end gap-2"><button onClick={() => setReviewing(null)} className="rounded-xl border px-4 py-2 text-sm">Cancel</button><button onClick={() => review("needs_improvement")} className="rounded-xl bg-rose-600 px-4 py-2 text-sm text-white">Needs improvement</button><button onClick={() => review("completed")} className="rounded-xl bg-emerald-600 px-4 py-2 text-sm text-white">Accept & complete</button></div></div></div>}</div>;
}

function TaskCard({ task, action }: { task: Task; action?: React.ReactNode }) { return <article className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-start justify-between gap-3"><h3 className="font-bold text-slate-900">{task.title}</h3><span className={`shrink-0 rounded-full px-3 py-1 text-xs font-semibold ${colors[task.status]}`}>{labels[task.status]}</span></div><p className="mt-3 whitespace-pre-wrap text-sm leading-6 text-slate-600">{task.description}</p><p className="mt-3 text-xs text-slate-500">{task.assignedToName} · Assigned by {task.assignedByName}{task.dueDate ? ` · Due ${new Date(task.dueDate).toLocaleDateString()}` : ""}</p>{task.reviewerRemarks && <div className="mt-3 rounded-xl bg-rose-50 p-3 text-sm text-rose-800"><strong>Reviewer remarks:</strong> {task.reviewerRemarks}</div>}<div className="mt-4">{action}</div></article>; }
function Empty() { return <div className="rounded-3xl border border-dashed border-slate-300 p-8 text-center text-sm text-slate-500"><ClipboardList className="mx-auto mb-3 h-7 w-7"/>No tasks to show yet.</div>; }
